server:
  port: 8085
  
spring:  application:    name: CONFIG-SERVER
    
  cloud:    config:      server:        git:          uri: https://github.com/abhijeet-26/Microservice-Configuration
          clone-on-start: true
    
